platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Demo' do

  # Our libraries
  pod 'ReactiveMoya', :git => "https://github.com/Moya/Moya"
  pod 'RxMoya', :git => "https://github.com/Moya/Moya", :branch => 'tvOS'
  pod 'Moya', :git => "https://github.com/Moya/Moya", :branch => 'tvOS'

  # Fix for `Alamofire` with `tvOS` support
  pod 'Alamofire', :git => "https://github.com/Alamofire/Alamofire", :branch => "tvOS"
end

target 'DemoTests' do

  pod 'Quick', :git => 'https://github.com/Quick/Quick'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble'
  pod 'OHHTTPStubs'

end
